### ISSUE TITLE
Need to update freedesktop Sdk version from 22.08 to something newer

### ISSUE THREAD

**Issue by phase1geo** [flathub/com.github.phase1geo.minder#39]
Version 22.08 of the freedesktop SDK/Platform is now considered end-of-life.  This version should be updated to something newer which is supported.

**Comment by CodeShakingSheep** [comment]
I second this. Minder is the last app on my system which uses FreeDesktop SDK 22.08 (which I want to get rid of as it consumes >2.5GB of disk space). So, I kindly want to ask if there's any ETA for the runtime update? Thank you.
