### ISSUE TITLE
minder crashes on startup

### ISSUE THREAD

**Issue by tronta** [flathub/com.github.phase1geo.minder#4]
for me, on Fedora 34 and Ubuntu 10.4 minder crashes immediately after startup on the latest version (1.12.2) with:
```
I/O warning : failed to load external entity "/home/xxxx/.var/app/com.github.phase1geo.minder/data/minder/favorites.xml"
I/O warning : failed to load external entity "/home/xxxx/.var/app/com.github.phase1geo.minder/data/minder/exports.xml"
free(): invalid pointer
```

**Comment by danilown** [comment]
This problem seems to have been fixed on the next release of Minder. As we wait for it to be released, one workaround that I've found is to use [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) and turn the `D-Bus system bus` switch on.

**Comment by tronta** [comment]
yes, right. Unfortunately there seems be an other reason for a crash, but this looks good.
